# Generated by Django 6.0.5 on 2026-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(default=list, help_text='List of recipient email addresses.')),
                ('cc', models.JSONField(blank=True, default=list, help_text='List of CC email addresses.')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses.')),
                ('email_from', models.EmailField(help_text='Sender email address used for this message.', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
