# Generated by Django 6.0.5 on 2026-05-15 01:04

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    EmailLog = apps.get_model('emails', 'EmailLog')
    EmailLog.objects.filter(account_id__isnull=True).update(account_id=1)
    EmailTemplate = apps.get_model('emails', 'EmailTemplate')
    EmailTemplate.objects.filter(account_id__isnull=True).update(account_id=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_emaillog_account_emailtemplate_account'),
        ('users', '0002_alter_user_account'),
    ]

    operations = [
        migrations.RunPython(forwards, noop),
        migrations.AlterField(
            model_name='emaillog',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
    ]
