# Generated by Django 6.0.5 on 2026-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_emaillog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('users', 'Users'), ('bookings', 'Bookings')], db_column='type', db_index=True, max_length=32),
        ),
    ]
