# Generated by Django 6.0.5 on 2026-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_seed_calendar_email_templates_per_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('users', 'Users'), ('bookings', 'Bookings'), ('calendar', 'Calendar')], db_column='type', db_index=True, max_length=32),
        ),
    ]
