# Generated by Django 6.0.5 on 2026-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0023_emaillog_created_at_company_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('users', 'Users'), ('bookings', 'Quotations'), ('calendar', 'Calendar')], db_column='type', db_index=True, max_length=32),
        ),
    ]
