# Generated by Django 6.0.5 on 2026-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0024_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('users', 'Users'), ('quotations', 'Quotations'), ('calendar', 'Calendar')], db_column='type', db_index=True, max_length=32),
        ),
    ]
