# Generated by Django 6.0.5 on 2026-05-15 01:04

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')
    Contact.objects.filter(account_id__isnull=True).update(account_id=1)
    ContactNumber = apps.get_model('contacts', 'ContactNumber')
    ContactNumber.objects.filter(account_id__isnull=True).update(account_id=1)
    ContactAddress = apps.get_model('contacts', 'ContactAddress')
    ContactAddress.objects.filter(account_id__isnull=True).update(account_id=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_account_contactaddress_account_and_more'),
        ('users', '0002_alter_user_account'),
    ]

    operations = [
        migrations.RunPython(forwards, noop),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
    ]
