# Generated by Django 6.0.5 on 2026-05-15 01:04

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Account = apps.get_model('users', 'Account')
    if not Account.objects.filter(pk=1).exists():
        Account.objects.create(
            pk=1,
            name='Default',
            status='active',
            is_active=True,
        )
    User = apps.get_model('users', 'User')
    User.objects.filter(account_id__isnull=True).update(account_id=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, noop),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='users',
                to='users.account',
            ),
        ),
    ]
