# Generated by Django 6.0.5 on 2026-05-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emaillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
