# Generated by Django 6.0.5 on 2026-05-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_emaillog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='password_reset_tokens',
        ),
    ]
