# Generated by Django 6.0.5 on 2026-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_account_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paymongo_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
