# Generated by Django 6.0.5 on 2026-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='', help_text='Secured API URL for the user profile photo download route.', max_length=512),
        ),
    ]
