# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations, models
import django.db.models.deletion


FEATURE_KEYS = (
    'dashboard',
    'calendar',
    'bookings',
    'contacts',
    'users',
    'emails',
    'file_manager',
    'reports',
    'settings',
    'account_settings',
    'companies_settings',
    'supplier_settings',
    'booking_settings_statuses',
    'booking_settings_form_templates',
    'email_templates',
    'subscription',
)


def backfill_owner_roles(apps, schema_editor):
    Account = apps.get_model('users', 'Account')
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')

    for account in Account.objects.all().iterator():
        role, _created = Role.objects.get_or_create(
            account_id=account.id,
            name='Owner',
            defaults={'is_default': True},
        )
        if not role.is_default:
            role.is_default = True
            role.save(update_fields=['is_default'])

        # Ensure write on all known features.
        for key in FEATURE_KEYS:
            RolePermission.objects.update_or_create(
                role_id=role.id,
                feature_key=key,
                defaults={'access': 'write'},
            )

        # Assign all existing users in the account to Owner unless already set.
        User.objects.filter(account_id=account.id, role_id__isnull=True).update(
            role_id=role.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.account')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['account_id', 'name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100)),
                ('access', models.CharField(choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write')], default='none', max_length=10)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role_id', 'feature_key'],
                'unique_together': {('role', 'feature_key')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role'),
        ),
        migrations.RunPython(backfill_owner_roles, migrations.RunPython.noop),
    ]

