# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations


FEATURE_KEYS = (
    'dashboard',
    'calendar',
    'bookings',
    'contacts',
    'users',
    'emails',
    'file_manager',
    'reports',
    'settings',
    'account_settings',
    'companies_settings',
    'supplier_settings',
    'booking_settings_statuses',
    'booking_settings_form_templates',
    'email_templates',
    'subscription',
)


def grant_platform_admin_to_former_flagged_users(apps, schema_editor):
    """Users who had is_admin=True keep platform staff access via their role."""
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')

    for user in User.objects.filter(is_admin=True).iterator():
        role_id = user.role_id
        if role_id is None:
            role, _created = Role.objects.get_or_create(
                account_id=user.account_id,
                name='Owner',
                defaults={'is_default': True},
            )
            for key in FEATURE_KEYS:
                RolePermission.objects.update_or_create(
                    role_id=role.id,
                    feature_key=key,
                    defaults={'access': 'write'},
                )
            User.objects.filter(pk=user.pk).update(role_id=role.id)
            role_id = role.id
        RolePermission.objects.update_or_create(
            role_id=role_id,
            feature_key='platform_admin',
            defaults={'access': 'write'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_roles_and_permissions'),
    ]

    operations = [
        migrations.RunPython(
            grant_platform_admin_to_former_flagged_users,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
