# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations

NEW_FEATURES = (
    'roles_permissions',
    'calendar_settings',
)

# Map new feature -> source feature to copy access from (when present).
COPY_FROM = {
    'roles_permissions': 'settings',
    'calendar_settings': 'calendar',
}


def add_feature_permissions(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')

    for role in Role.objects.all().iterator():
        for feature_key in NEW_FEATURES:
            existing = RolePermission.objects.filter(
                role_id=role.id,
                feature_key=feature_key,
            ).first()
            if existing is not None:
                continue

            source_key = COPY_FROM[feature_key]
            source = RolePermission.objects.filter(
                role_id=role.id,
                feature_key=source_key,
            ).first()
            access = source.access if source is not None else 'none'
            if role.name == 'Owner' and access == 'none':
                access = 'write'

            RolePermission.objects.create(
                role_id=role.id,
                feature_key=feature_key,
                access=access,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_user_is_admin'),
    ]

    operations = [
        migrations.RunPython(add_feature_permissions, migrations.RunPython.noop),
    ]
