# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations

ADMIN_FEATURES = (
    'admin_company_verification',
    'admin_emails',
    'admin_payouts',
    'admin_system_notifications',
    'admin_support',
)


def copy_platform_admin_to_admin_features(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')

    for role in Role.objects.all().iterator():
        source = RolePermission.objects.filter(
            role_id=role.id,
            feature_key='platform_admin',
        ).first()
        access = source.access if source is not None else 'none'

        for feature_key in ADMIN_FEATURES:
            existing = RolePermission.objects.filter(
                role_id=role.id,
                feature_key=feature_key,
            ).first()
            if existing is not None:
                continue
            if access == 'none':
                continue
            RolePermission.objects.create(
                role_id=role.id,
                feature_key=feature_key,
                access=access,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_roles_permissions_calendar_settings_features'),
    ]

    operations = [
        migrations.RunPython(
            copy_platform_admin_to_admin_features,
            migrations.RunPython.noop,
        ),
    ]
