# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations


def remove_subscription_permissions(apps, schema_editor):
    RolePermission = apps.get_model('users', 'RolePermission')
    RolePermission.objects.filter(feature_key='subscription').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_admin_feature_permissions'),
    ]

    operations = [
        migrations.RunPython(
            remove_subscription_permissions,
            migrations.RunPython.noop,
        ),
    ]
