# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations

SOURCE_KEY = 'booking_settings_form_templates'
TARGET_KEY = 'booking_settings_statuses'


def merge_form_templates_into_booking_settings(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')

    rank = {'none': 0, 'read': 1, 'write': 2}

    for role in Role.objects.all().iterator():
        target = RolePermission.objects.filter(
            role_id=role.id,
            feature_key=TARGET_KEY,
        ).first()
        source = RolePermission.objects.filter(
            role_id=role.id,
            feature_key=SOURCE_KEY,
        ).first()
        if source is None:
            continue

        source_level = rank.get(source.access, 0)
        target_level = rank.get(target.access, 0) if target is not None else 0
        merged = source_level if source_level > target_level else target_level
        merged_access = 'write' if merged == 2 else 'read' if merged == 1 else 'none'

        if target is None and merged_access != 'none':
            RolePermission.objects.create(
                role_id=role.id,
                feature_key=TARGET_KEY,
                access=merged_access,
            )
        elif target is not None and merged_access != target.access:
            target.access = merged_access
            target.save(update_fields=['access'])

        source.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_subscription_permission_feature'),
    ]

    operations = [
        migrations.RunPython(
            merge_form_templates_into_booking_settings,
            migrations.RunPython.noop,
        ),
    ]
