# Generated by Django 6.0.5 on 2026-05-26

from django.db import migrations

FEATURE_KEY = 'change_company'
SOURCE_KEYS = ('users', 'emails', 'bookings')


def add_change_company_permissions(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')
    rank = {'none': 0, 'read': 1, 'write': 2}

    for role in Role.objects.all().iterator():
        existing = RolePermission.objects.filter(
            role_id=role.id,
            feature_key=FEATURE_KEY,
        ).first()
        if existing is not None:
            continue

        merged = 0
        for source_key in SOURCE_KEYS:
            source = RolePermission.objects.filter(
                role_id=role.id,
                feature_key=source_key,
            ).first()
            if source is not None:
                merged = max(merged, rank.get(source.access, 0))

        if role.name == 'Owner' and merged == 0:
            merged = 2

        if merged == 0:
            continue

        access = 'write' if merged == 2 else 'read'
        RolePermission.objects.create(
            role_id=role.id,
            feature_key=FEATURE_KEY,
            access=access,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_booking_form_templates_permission'),
    ]

    operations = [
        migrations.RunPython(
            add_change_company_permissions,
            migrations.RunPython.noop,
        ),
    ]
