# Generated by Django 5.1.6 on 2026-06-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_rename_companykybverification_status_paymongo_status'),
        ('users', '0037_admin_subscriptions_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        db_column='account_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='users.account',
                    ),
                ),
                (
                    'admin_user',
                    models.ForeignKey(
                        db_column='admin_user_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='impersonations_started',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        blank=True,
                        db_column='company_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='companies.company',
                    ),
                ),
                (
                    'target_user',
                    models.ForeignKey(
                        db_column='target_user_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='impersonations_received',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'impersonation_logs',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
