# Generated by Django 6.0.5 on 2026-06-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_rename_supplier_setting_tier_id_to_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersettingpackage',
            name='supplier_setting',
            field=models.ForeignKey(db_column='supplier_setting_id', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='suppliers.suppliersetting'),
        ),
    ]
