# Generated by Django 6.0.5 on 2026-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_seed_calendar_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='repeat_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
