# Generated by Django 6.0.5 on 2026-05-19 13:20

from django.db import migrations, models
from django.utils import timezone


def backfill_effectivity_dates(apps, schema_editor):
    PackageVersion = apps.get_model('packages', 'PackageVersion')
    for version in PackageVersion.objects.filter(effectivity_date__isnull=True).iterator():
        when = version.created_at
        version.effectivity_date = when.date() if when else timezone.localdate()
        version.save(update_fields=['effectivity_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_package_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='effectivity_date',
            field=models.DateField(blank=True, db_column='effectivity_date', null=True),
        ),
        migrations.RunPython(backfill_effectivity_dates, migrations.RunPython.noop),
    ]
