# Generated by Django 6.0.5 on 2026-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_packageversion_effectivity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='effectivity_date',
            field=models.DateTimeField(blank=True, db_column='effectivity_date', null=True),
        ),
    ]
