# Generated by Django 6.0.5 on 2026-05-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_packageversion_effectivity_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageitem',
            options={'ordering': ['sort_order', 'title', 'id']},
        ),
        migrations.AddField(
            model_name='packageitem',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='packages.packageitem'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
