# Generated by Django 6.0.5 on 2026-06-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_packageprice_tier_to_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageprice',
            options={'ordering': ['package_id', 'id']},
        ),
    ]
