"""
Django settings for planningwithyou project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

CORS_ALLOW_ALL_ORIGINS = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Google OAuth token responses may include scopes beyond those requested (incremental auth).
os.environ.setdefault('OAUTHLIB_RELAX_TOKEN_SCOPE', '1')


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if value is None or not str(value).strip():
        raise ImproperlyConfigured(
            f'Set {name} in the project root .env file (see .env.example).'
        )
    return value


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv_env(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def _host_from_url(url: str) -> str:
    from urllib.parse import urlparse

    if not url:
        return ''
    return (urlparse(url.strip()).hostname or '').strip()


def _merge_unique_hosts(*host_lists: list[str]) -> list[str]:
    merged: list[str] = []
    seen: set[str] = set()
    for hosts in host_lists:
        for host in hosts:
            item = host.strip()
            if item and item not in seen:
                seen.add(item)
                merged.append(item)
    return merged


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = _require_env('SECRET_KEY')

DEBUG = _env_bool('DEBUG', default=True)

# ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = _merge_unique_hosts(
    [
        'api.planningwithyou.com',
        'app.planningwithyou.com',
        'planningwithyou.com',
        'www.planningwithyou.com',
        'localhost',
        '127.0.0.1',
    ],
    _csv_env('ALLOWED_HOSTS', ''),
    ['.ngrok-free.app', '.ngrok.io', '.ngrok.app'] if DEBUG else [],
)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://app.planningwithyou.com",
    "https://www.planningwithyou.com",
    "https://planningwithyou.com",
]

# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'countries',
    'config',
    'users',
    'companies.apps.CompaniesConfig',
    'emails.apps.EmailsConfig',
    'documents',
    'contacts',
    'bookings',
    'calendars',
    'suppliers',
    'subscriptions',
    'packages',
    'payments',
    'system_notifications',
    'system_settings',
    'support',
    'template_studio',
    'ai_assistant.apps.AiAssistantConfig',
]

MIDDLEWARE = [
    'config.middleware.ErrorLoggingMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # MUST be here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'companies.middleware.CompanyTimezoneMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'planningwithyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'planningwithyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _require_env('POSTGRES_DB'),
        'USER': _require_env('POSTGRES_USER'),
        'PASSWORD': _require_env('POSTGRES_PASSWORD'),
        'HOST': (os.environ.get('POSTGRES_HOST') or 'localhost').strip(),
        'PORT': (os.environ.get('POSTGRES_PORT') or '5432').strip(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File uploads (documents) — AWS S3 when configured, else local media/
USE_S3_STORAGE = _env_bool(
    'USE_S3_STORAGE',
    default=bool(os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()),
)

STORAGES = {
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if USE_S3_STORAGE:
    AWS_ACCESS_KEY_ID = _require_env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = _require_env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = _require_env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = (os.environ.get('AWS_S3_REGION_NAME') or 'us-east-1').strip()
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_QUERYSTRING_AUTH = _env_bool('AWS_S3_QUERYSTRING_AUTH', default=False)

    _s3_endpoint = os.environ.get('AWS_S3_ENDPOINT_URL', '').strip()
    if _s3_endpoint:
        AWS_S3_ENDPOINT_URL = _s3_endpoint

    _s3_custom_domain = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '').strip()
    if _s3_custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _s3_custom_domain

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    }

# Cross-origin requests from the Vite dev server (and similar local frontends).
# CORS_ALLOWED_ORIGINS = _csv_env(
#     'CORS_ALLOWED_ORIGINS',
#     'http://localhost:5173,http://127.0.0.1:5173,https://planningwithyou.com,https://www.planningwithyou.com,https://app.planningwithyou.com,https://api.planningwithyou.com',
# )

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://planningwithyou.com",
    "https://www.planningwithyou.com",
    "https://app.planningwithyou.com",
]
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Disposition']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.jwt.SessionJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'config.drf_exception_handler.custom_exception_handler',
}



MAILJET_API_KEY = os.environ.get('MAILJET_API_KEY', '')
MAILJET_SECRET_KEY = os.environ.get('MAILJET_SECRET_KEY', '')
MAILJET_SEND_FROM = os.environ.get('MAILJET_SEND_FROM', '')
MAILJET_SENDER_NAME = os.environ.get('MAILJET_SENDER_NAME', 'Planning With You')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
API_PUBLIC_BASE_URL = os.environ.get('API_PUBLIC_BASE_URL', 'http://localhost:8000')

ALLOWED_HOSTS = _merge_unique_hosts(
    ALLOWED_HOSTS,
    [
        host
        for host in (
            _host_from_url(API_PUBLIC_BASE_URL),
            _host_from_url(os.environ.get('XENDIT_RETURN_URL_BASE', '')),
        )
        if host
    ],
)

# Google Calendar OAuth (Calendar Settings → Calendar Integrations)
GOOGLE_CALENDAR_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_CALENDAR_OAUTH_CLIENT_ID', '')
GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET = os.environ.get(
    'GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET',
    '',
)

# Gmail OAuth (Email Settings → Email Integration).
# Prefer GOOGLE_EMAIL_*; see gmail_service for Calendar OAuth fallback.
GOOGLE_EMAIL_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_EMAIL_OAUTH_CLIENT_ID', '')
GOOGLE_EMAIL_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_EMAIL_OAUTH_CLIENT_SECRET', '')

# PayMongo (platform account — public booking payment links)
PAYMONGO_SECRET_KEY = os.environ.get('PAYMONGO_SECRET_KEY', '')
PAYMONGO_WEBHOOK_SECRET = os.environ.get('PAYMONGO_WEBHOOK_SECRET', '')
# PayMongo Platforms: parent wallet id for split (1% platform fee to this merchant).
PAYMONGO_PLATFORM_MERCHANT_ID = os.environ.get('PAYMONGO_PLATFORM_MERCHANT_ID', '')
# Basis points taken by platform on net (100 = 1%).
PAYMONGO_PLATFORM_FEE_BPS = int(os.environ.get('PAYMONGO_PLATFORM_FEE_BPS', '100') or '100')
# Optional header to scope v1 API calls to a linked child account (confirm with PayMongo).
PAYMONGO_CHILD_ACCOUNT_HEADER = os.environ.get(
    'PAYMONGO_CHILD_ACCOUNT_HEADER',
    'Paymongo-Account-Id',
)
# POST child merchant under platform (full URL or path).
PAYMONGO_MERCHANT_CHILDREN_URL = (
    os.environ.get(
        'PAYMONGO_MERCHANT_CHILDREN_URL',
        'https://api.paymongo.com/v1/merchants/children',
    )
    or 'https://api.paymongo.com/v1/merchants/children'
).strip()
# Hosted KYB: base URL or template with {merchant_id} (trailing slash optional).
PAYMONGO_ONBOARDING_URL = (
    os.environ.get(
        'PAYMONGO_ONBOARDING_URL',
        'https://onboarding.paymongo.com/onboarding/merchants',
    )
    or 'https://onboarding.paymongo.com/onboarding/merchants'
).strip()

# Xendit (subscription billing + xenPlatform company KYB)
XENDIT_SECRET_KEY = os.environ.get('XENDIT_SECRET_KEY', '').strip()
# Unused for company KYB — Xendit MANAGED accounts use email invitations, not hosted URLs.
XENDIT_ONBOARDING_URL = (
    os.environ.get(
        'XENDIT_ONBOARDING_URL',
        '',
    )
    or ''
).strip()
# Payment Sessions require https return URLs (use ngrok in local dev if FRONTEND_URL is http).
XENDIT_RETURN_URL_BASE = (
    os.environ.get('XENDIT_RETURN_URL_BASE', '').strip().rstrip('/') or None
)
XENDIT_WEBHOOK_TOKEN = os.environ.get('XENDIT_WEBHOOK_TOKEN', '').strip()
# xenPlatform: percent of net settlement routed to master account on payment links (1 = 1%).
XENDIT_PLATFORM_FEE_PERCENT = os.environ.get('XENDIT_PLATFORM_FEE_PERCENT', '1') or '1'
# Optional pre-created split rule id (skips auto-provision via Split Rules API).
XENDIT_PLATFORM_SPLIT_RULE_ID = os.environ.get('XENDIT_PLATFORM_SPLIT_RULE_ID', '').strip()
# xenPlatform master Business ID — destination for platform fee split rules.
XENDIT_PLATFORM_MASTER_ACCOUNT_ID = os.environ.get(
    'XENDIT_PLATFORM_MASTER_ACCOUNT_ID',
    '',
).strip()

PASSWORD_RESET_TOKEN_LIFETIME_HOURS = int(
    os.environ.get('PASSWORD_RESET_TOKEN_LIFETIME_HOURS', 24),
)
EMAIL_VERIFICATION_TOKEN_LIFETIME_HOURS = int(
    os.environ.get('EMAIL_VERIFICATION_TOKEN_LIFETIME_HOURS', 72),
)

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Not working in local development
if CELERY_BROKER_URL.startswith("rediss://"):
    CELERY_BROKER_USE_SSL = {
        "ssl_cert_reqs": ssl.CERT_NONE,
    }

    CELERY_REDIS_BACKEND_USE_SSL = {
        "ssl_cert_reqs": ssl.CERT_NONE,
    }

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 60)),
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 7)),
    ),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_REFRESH_SERIALIZER': 'users.jwt.SessionTokenRefreshSerializer',
}

# AI assistant (OpenAI). Set OPENAI_API_KEY to enable.
# AI_ASSISTANT_PLANS: subscription slugs allowed to use AI (default: AI Plus only).
OPENAI_API_KEY = (os.environ.get('OPENAI_API_KEY') or '').strip()
OPENAI_API_BASE = (os.environ.get('OPENAI_API_BASE') or '').strip()
AI_ASSISTANT_MODEL = (os.environ.get('AI_ASSISTANT_MODEL') or 'gpt-4o-mini').strip()
AI_ASSISTANT_PLANS = _csv_env('AI_ASSISTANT_PLANS', 'ai,admin')
AI_ASSISTANT_TIMEOUT = int(os.environ.get('AI_ASSISTANT_TIMEOUT', '60'))
