"""
Django settings for planningwithyou project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

CORS_ALLOW_ALL_ORIGINS = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if value is None or not str(value).strip():
        raise ImproperlyConfigured(
            f'Set {name} in the project root .env file (see .env.example).'
        )
    return value


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv_env(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = _require_env('SECRET_KEY')

DEBUG = _env_bool('DEBUG', default=True)

ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'countries',
    'config',
    'users',
    'companies',
    'emails',
    'documents',
    'contacts',
    'bookings',
    'calendars',
    'suppliers',
    'subscriptions',
    'packages',
    'payments',
    'system_notifications',
    'system_settings',
    'support',
    'template_studio',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # MUST be here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'planningwithyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'planningwithyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _require_env('POSTGRES_DB'),
        'USER': _require_env('POSTGRES_USER'),
        'PASSWORD': _require_env('POSTGRES_PASSWORD'),
        'HOST': (os.environ.get('POSTGRES_HOST') or 'localhost').strip(),
        'PORT': (os.environ.get('POSTGRES_PORT') or '5432').strip(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File uploads (documents) — AWS S3 when configured, else local media/
USE_S3_STORAGE = _env_bool(
    'USE_S3_STORAGE',
    default=bool(os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()),
)

STORAGES = {
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if USE_S3_STORAGE:
    AWS_ACCESS_KEY_ID = _require_env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = _require_env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = _require_env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = (os.environ.get('AWS_S3_REGION_NAME') or 'us-east-1').strip()
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_QUERYSTRING_AUTH = _env_bool('AWS_S3_QUERYSTRING_AUTH', default=False)

    _s3_endpoint = os.environ.get('AWS_S3_ENDPOINT_URL', '').strip()
    if _s3_endpoint:
        AWS_S3_ENDPOINT_URL = _s3_endpoint

    _s3_custom_domain = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '').strip()
    if _s3_custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _s3_custom_domain

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    }

# Cross-origin requests from the Vite dev server (and similar local frontends).
CORS_ALLOWED_ORIGINS = _csv_env(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,https://planningwithyou.com,https://www.planningwithyou.com,https://app.planningwithyou.com,https://api.planningwithyou.com',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.jwt.SessionJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}



MAILJET_API_KEY = os.environ.get('MAILJET_API_KEY', '')
MAILJET_SECRET_KEY = os.environ.get('MAILJET_SECRET_KEY', '')
MAILJET_SEND_FROM = os.environ.get('MAILJET_SEND_FROM', '')
MAILJET_SENDER_NAME = os.environ.get('MAILJET_SENDER_NAME', 'Planning With You')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
API_PUBLIC_BASE_URL = os.environ.get('API_PUBLIC_BASE_URL', 'http://localhost:8000')

# PayMongo (platform account — public booking payment links)
PAYMONGO_SECRET_KEY = os.environ.get('PAYMONGO_SECRET_KEY', '')
PAYMONGO_WEBHOOK_SECRET = os.environ.get('PAYMONGO_WEBHOOK_SECRET', '')
# PayMongo Platforms: parent wallet id for split (1% platform fee to this merchant).
PAYMONGO_PLATFORM_MERCHANT_ID = os.environ.get('PAYMONGO_PLATFORM_MERCHANT_ID', '')
# Basis points taken by platform on net (100 = 1%).
PAYMONGO_PLATFORM_FEE_BPS = int(os.environ.get('PAYMONGO_PLATFORM_FEE_BPS', '100') or '100')
# Optional header to scope v1 API calls to a linked child account (confirm with PayMongo).
PAYMONGO_CHILD_ACCOUNT_HEADER = os.environ.get(
    'PAYMONGO_CHILD_ACCOUNT_HEADER',
    'Paymongo-Account-Id',
)
# POST child merchant under platform (full URL or path).
PAYMONGO_MERCHANT_CHILDREN_URL = (
    os.environ.get(
        'PAYMONGO_MERCHANT_CHILDREN_URL',
        'https://api.paymongo.com/v1/merchants/children',
    )
    or 'https://api.paymongo.com/v1/merchants/children'
).strip()
# Hosted KYB: base URL or template with {merchant_id} (trailing slash optional).
PAYMONGO_ONBOARDING_URL = (
    os.environ.get(
        'PAYMONGO_ONBOARDING_URL',
        'https://onboarding.paymongo.com/onboarding/merchants',
    )
    or 'https://onboarding.paymongo.com/onboarding/merchants'
).strip()

PASSWORD_RESET_TOKEN_LIFETIME_HOURS = int(
    os.environ.get('PASSWORD_RESET_TOKEN_LIFETIME_HOURS', 24),
)
EMAIL_VERIFICATION_TOKEN_LIFETIME_HOURS = int(
    os.environ.get('EMAIL_VERIFICATION_TOKEN_LIFETIME_HOURS', 72),
)

# Celery
REDIS_HOST = "master.elasticache-redis.b2frse.apse1.cache.amazonaws.com"

REDIS_URL = f"rediss://{REDIS_HOST}:6379/0"

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_BROKER_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE,
}

CELERY_REDIS_BACKEND_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE,
}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 60)),
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 7)),
    ),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_REFRESH_SERIALIZER': 'users.jwt.SessionTokenRefreshSerializer',
}
