# Generated by Django 6.0.5 on 2026-05-14 06:24

from django.db import migrations


def create_default_folder(apps, schema_editor):
    DocumentFolder = apps.get_model('documents', 'DocumentFolder')
    Document = apps.get_model('documents', 'Document')
    folder, _ = DocumentFolder.objects.get_or_create(name='General')
    Document.objects.filter(folder__isnull=True).update(folder=folder)


def reverse_default_folder(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    Document.objects.all().update(folder=None)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfolder_document_deleted_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_folder, reverse_default_folder),
    ]
