# Generated by Django — AI assistant initial migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0060_quotationline_supplier_type'),
        ('companies', '0010_company_contact_email'),
        ('users', '0034_admin_error_logs_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('summarize', 'Summarize quotation'), ('draft_email', 'Draft quotation email')], max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('quotation', models.ForeignKey(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.quotation')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
