# Generated by Django 6.0.5 on 2026-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_account_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past due'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='team_seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
