# Generated by Django 6.0.5 on 2026-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_revamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='end_date',
            field=models.DateField(blank=True, help_text='End of prepaid period; null for lifetime Free.', null=True),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='PayMongo subscription id for paid plans.', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='start_date',
            field=models.DateField(help_text='Start of the current prepaid period.'),
        ),
    ]
