# Generated by Django 6.0.5 on 2026-05-29 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_studio', '0004_templateasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvitationRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(help_text='Canvas element id of the RSVP widget in the template document.', max_length=64)),
                ('fields_data', models.JSONField(default=dict, help_text='Dynamic field values keyed by field id from the RSVP form config.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_template', models.ForeignKey(db_column='invitation_template_id', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='template_studio.invitationtemplate')),
            ],
            options={
                'db_table': 'invitation_rsvps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation_template', 'element_id'], name='invitation__invitat_91ee43_idx')],
            },
        ),
    ]
