# Generated by Django 6.0.5 on 2026-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_studio', '0007_invitation_template_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtemplate',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Public invitation page views (used on RSVP analytics).'),
        ),
    ]
