# Generated by Django 6.0.5 on 2026-05-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_formtemplatefield_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplatefield',
            name='options',
        ),
        migrations.CreateModel(
            name='FormTemplateFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bookings.formtemplatefield')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
