# Generated by Django 6.0.5 on 2026-05-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_formtemplatefield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formtemplate',
            table='form_templates',
        ),
        migrations.AlterModelTable(
            name='formtemplatefield',
            table='form_template_fields',
        ),
        migrations.AlterModelTable(
            name='formtemplatefieldoption',
            table='form_template_field_options',
        ),
    ]
