# Generated by Django 6.0.5 on 2026-05-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingcolumn_bookingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcolumn',
            name='wip_limit',
        ),
    ]
