# Generated by Django 6.0.5 on 2026-05-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_bookingcolumn_wip_limit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingitem',
            table='bookings',
        ),
    ]
