# Generated by Django 6.0.5 on 2026-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookingitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
