# Generated by Django 6.0.5 on 2026-05-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_date_of_event_to_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.formtemplate'),
        ),
    ]
