# Generated by Django 6.0.5 on 2026-05-14 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_form_template_to_bookingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='bookings.bookingitem')),
            ],
            options={
                'db_table': 'booking_field_values',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
