# Generated by Django 6.0.5 on 2026-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_booking_field_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
