# Generated by Django 6.0.5 on 2026-05-15 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_add_is_default_to_formtemplate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcolumn',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
        migrations.AddField(
            model_name='bookingfieldvalue',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
        migrations.AddField(
            model_name='formtemplatefield',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
        migrations.AddField(
            model_name='formtemplatefieldoption',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.account'),
        ),
    ]
