# Generated by Django 6.0.5 on 2026-05-15 01:04

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    BookingColumn = apps.get_model('bookings', 'BookingColumn')
    BookingColumn.objects.filter(account_id__isnull=True).update(account_id=1)
    BookingItem = apps.get_model('bookings', 'BookingItem')
    BookingItem.objects.filter(account_id__isnull=True).update(account_id=1)
    BookingFieldValue = apps.get_model('bookings', 'BookingFieldValue')
    BookingFieldValue.objects.filter(account_id__isnull=True).update(account_id=1)
    FormTemplate = apps.get_model('bookings', 'FormTemplate')
    FormTemplate.objects.filter(account_id__isnull=True).update(account_id=1)
    FormTemplateField = apps.get_model('bookings', 'FormTemplateField')
    FormTemplateField.objects.filter(account_id__isnull=True).update(account_id=1)
    FormTemplateFieldOption = apps.get_model('bookings', 'FormTemplateFieldOption')
    FormTemplateFieldOption.objects.filter(account_id__isnull=True).update(account_id=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_bookingcolumn_account_bookingfieldvalue_account_and_more'),
        ('users', '0002_alter_user_account'),
    ]

    operations = [
        migrations.RunPython(forwards, noop),
        migrations.AlterField(
            model_name='bookingcolumn',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='bookingfieldvalue',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='formtemplatefield',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
        migrations.AlterField(
            model_name='formtemplatefieldoption',
            name='account',
            field=models.ForeignKey(
                db_column='account_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='users.account',
            ),
        ),
    ]
