# Generated by Django 6.0.5 on 2026-05-18 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_add_supplier_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingline',
            name='group_name',
            field=models.TextField(default='Suppliers'),
        ),
        migrations.AlterField(
            model_name='bookingline',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bookings.bookingitem'),
        ),
    ]
