# Generated by Django 6.0.5 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_GROUP_NAME = 'Suppliers'


def migrate_group_names_to_booking_groups(apps, schema_editor):
    BookingItem = apps.get_model('bookings', 'BookingItem')
    BookingLine = apps.get_model('bookings', 'BookingLine')
    BookingGroup = apps.get_model('bookings', 'BookingGroup')

    for booking in BookingItem.objects.all().iterator():
        lines = list(BookingLine.objects.filter(booking_id=booking.pk))
        if not lines:
            continue

        group_by_name = {}
        for line in lines:
            name = (line.group_name or '').strip() or DEFAULT_GROUP_NAME
            if name not in group_by_name:
                group_by_name[name] = BookingGroup.objects.create(
                    booking_id=booking.pk,
                    name=name,
                )

        for line in lines:
            name = (line.group_name or '').strip() or DEFAULT_GROUP_NAME
            line.booking_group_id = group_by_name[name].pk
            line.save(update_fields=['booking_group_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_bookingline_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                (
                    'booking',
                    models.ForeignKey(
                        db_column='booking_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='groups',
                        to='bookings.bookingitem',
                    ),
                ),
            ],
            options={
                'db_table': 'booking_groups',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookinggroup',
            constraint=models.UniqueConstraint(
                fields=('booking', 'name'),
                name='booking_groups_booking_name_uniq',
            ),
        ),
        migrations.AddField(
            model_name='bookingline',
            name='booking_group',
            field=models.ForeignKey(
                blank=True,
                db_column='booking_group_id',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lines',
                to='bookings.bookinggroup',
            ),
        ),
        migrations.RunPython(migrate_group_names_to_booking_groups, noop_reverse),
        migrations.RemoveField(
            model_name='bookingline',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='bookingline',
            name='booking_group',
            field=models.ForeignKey(
                db_column='booking_group_id',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lines',
                to='bookings.bookinggroup',
            ),
        ),
    ]
