# Generated by Django 6.0.5 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_bookinggroup_and_line_booking_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingline',
            name='booking_group',
            field=models.ForeignKey(
                db_column='booking_group_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lines',
                to='bookings.bookinggroup',
            ),
        ),
    ]
