# Generated by Django 6.0.5 on 2026-05-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_rename_statuses_table'),
        ('companies', '0002_company_supplier_type'),
        ('contacts', '0005_contact_company'),
        ('users', '0016_remove_account_supplier_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingitem',
            name='bookings_company_unique_id_uniq',
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='pdf',
            field=models.TextField(blank=True, default='', help_text='Absolute API URL for the secured booking PDF download route.'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.bookingstatus'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('account', 'unique_id'), name='bookings_account_unique_id_uniq'),
        ),
    ]
