# Generated by Django 6.0.5 on 2026-05-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_remove_bookingitem_bookings_company_unique_id_uniq_and_more'),
        ('companies', '0002_company_supplier_type'),
        ('packages', '0005_package_package_version'),
        ('suppliers', '0010_tier_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingline',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_lines', to='companies.company'),
        ),
        migrations.AddField(
            model_name='bookingline',
            name='package_version',
            field=models.ForeignKey(blank=True, db_column='package_version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_lines', to='packages.packageversion'),
        ),
        migrations.AddField(
            model_name='bookingline',
            name='tier',
            field=models.ForeignKey(blank=True, db_column='tier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_lines', to='suppliers.tier'),
        ),
    ]
