# Generated by Django 6.0.5 on 2026-05-21 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_booking_payment_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_payment_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingpaymentlink',
            name='public_token',
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
