# Generated by Django 6.0.5 on 2026-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_bookingpayment_fee_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quote portion credited to the booking balance.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross amount the customer paid (PayMongo ``amount``).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after PayMongo fee (``net_amount`` on the payment).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (1% of base) from the payment link.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PayMongo processing fee (``fee`` on the payment).', max_digits=12),
        ),
    ]
