# Generated by Django 6.0.5 on 2026-05-26 01:09

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename indexes only when the old name is still present (idempotent)."""
    connection = schema_editor.connection

    renames = (
        ('history_resource_created_idx', 'history_resourc_a2be40_idx'),
        ('history_booking_created_idx', 'history_booking_02b548_idx'),
        ('history_account_created_idx', 'history_account_83bed0_idx'),
    )
    with connection.cursor() as cursor:
        for old_name, new_name in renames:
            cursor.execute(
                """
                SELECT 1 FROM pg_indexes
                WHERE tablename = 'history' AND indexname = %s
                """,
                [old_name],
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"',
                )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0045_history_resource_fields'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='history',
                    new_name='history_resourc_a2be40_idx',
                    old_name='history_resource_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='history',
                    new_name='history_booking_02b548_idx',
                    old_name='history_booking_created_idx',
                ),
                migrations.RenameIndex(
                    model_name='history',
                    new_name='history_account_83bed0_idx',
                    old_name='history_account_created_idx',
                ),
            ],
        ),
    ]
