# Generated by Django 6.0.5 on 2026-05-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0043_bookingpaymentreceipt'),
        ('bookings', '0048_history_form_template_choices'),
    ]

    operations = [
    ]
