# Generated by Django 6.0.5 on 2026-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0054_bookingstatus_company_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='resource_type',
            field=models.CharField(choices=[('booking', 'Quotation'), ('account', 'Account'), ('company', 'Company'), ('user', 'User'), ('contact', 'Contact'), ('supplier_setting', 'Supplier setting'), ('booking_status', 'Quotation status'), ('email_template', 'Email template'), ('form_template', 'Form template')], default='booking', max_length=32),
        ),
    ]
