# Sync Django migration state after 0056 renamed constraints/indexes in SQL.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0056_rename_bookings_to_quotations'),
        ('companies', '0010_company_contact_email'),
        ('contacts', '0005_contact_company'),
        ('packages', '0012_package_required_downpayment_amount'),
        ('suppliers', '0010_tier_company'),
        ('users', '0034_admin_error_logs_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='quotation',
                    name='bookings_account_unique_id_uniq',
                ),
                migrations.RemoveConstraint(
                    model_name='quotationgroup',
                    name='booking_groups_booking_name_uniq',
                ),
                migrations.RemoveConstraint(
                    model_name='quotationuniqueidsequence',
                    name='booking_unique_id_seq_company_year_uniq',
                ),
                migrations.RemoveIndex(
                    model_name='history',
                    name='history_quotati_a0bab6_idx',
                ),
                migrations.AlterField(
                    model_name='history',
                    name='actor',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='actor_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotation_history_entries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name='history',
                    name='quotation',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='quotation_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='history_entries',
                        to='bookings.quotation',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotation',
                    name='company',
                    field=models.ForeignKey(
                        db_column='company_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='quotations',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotation',
                    name='contact',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='contact_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotations',
                        to='contacts.contact',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotation',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='created_by',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotations_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name='quotation',
                    name='pdf',
                    field=models.TextField(
                        blank=True,
                        default='',
                        help_text='Absolute API URL for the secured quotation PDF download route.',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationgroup',
                    name='quotation',
                    field=models.ForeignKey(
                        db_column='quotation_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='groups',
                        to='bookings.quotation',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationline',
                    name='company',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='company_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotation_lines',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationline',
                    name='package_version',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='package_version_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotation_lines',
                        to='packages.packageversion',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationline',
                    name='quotation_group',
                    field=models.ForeignKey(
                        db_column='quotation_group_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='bookings.quotationgroup',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationline',
                    name='tier',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='tier_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotation_lines',
                        to='suppliers.tier',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpayment',
                    name='base_amount',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Quote portion credited to the quotation balance.',
                        max_digits=12,
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpayment',
                    name='company',
                    field=models.ForeignKey(
                        db_column='company_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='quotation_payments',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpayment',
                    name='quotation',
                    field=models.ForeignKey(
                        db_column='quotation_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='bookings.quotation',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentlink',
                    name='company',
                    field=models.ForeignKey(
                        db_column='company_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='quotation_payment_links',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentlink',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quotation_payment_links_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentlink',
                    name='quotation',
                    field=models.ForeignKey(
                        db_column='quotation_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_links',
                        to='bookings.quotation',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentreceipt',
                    name='company',
                    field=models.ForeignKey(
                        db_column='company_id',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='quotation_payment_receipts',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentreceipt',
                    name='quotation',
                    field=models.ForeignKey(
                        db_column='quotation_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_receipts',
                        to='bookings.quotation',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationpaymentreceipt',
                    name='quotation_payment',
                    field=models.OneToOneField(
                        db_column='quotation_payment_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='receipt',
                        to='bookings.quotationpayment',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationstatus',
                    name='company',
                    field=models.ForeignKey(
                        db_column='company_id',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quotation_statuses',
                        to='companies.company',
                    ),
                ),
                migrations.AlterField(
                    model_name='quotationstatus',
                    name='tags',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='quotation_statuses',
                        to='bookings.tag',
                    ),
                ),
                migrations.AddIndex(
                    model_name='history',
                    index=models.Index(
                        fields=['quotation', '-created_at'],
                        name='history_quotati_a0bab6_idx',
                    ),
                ),
                migrations.AddConstraint(
                    model_name='quotation',
                    constraint=models.UniqueConstraint(
                        fields=('account', 'unique_id'),
                        name='quotations_account_unique_id_uniq',
                    ),
                ),
                migrations.AddConstraint(
                    model_name='quotationgroup',
                    constraint=models.UniqueConstraint(
                        fields=('quotation', 'name'),
                        name='quotation_groups_quotation_name_uniq',
                    ),
                ),
                migrations.AddConstraint(
                    model_name='quotationuniqueidsequence',
                    constraint=models.UniqueConstraint(
                        fields=('company', 'year'),
                        name='quotation_unique_id_seq_company_year_uniq',
                    ),
                ),
            ],
        ),
    ]
